services:
  nr1-web:
    image: nr1-web:latest
    ports:
      - "8080:80"
    container_name: nr1-web-app
    restart: unless-stopped
    networks:
      - projectbase_default

networks:
  projectbase_default:
    external: true