services:
  nr1-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nr1-web:local
    ports:
      - "8080:80"
    container_name: nr1-web-app
    restart: unless-stopped
    networks:
      - projectbase_default

networks:
  projectbase_default:
    external: true